const $=s=>document.querySelector(s);
const teamsEl=$('#teams'),statusEl=$('#status'),namesEl=$('#playerNames'),versusEl=$('#versusResult');
const wheelEl=$('#rouletteWheel'),wheelMarkersEl=$('#wheelMarkers'),rouletteOptionsEl=$('#rouletteOptions');
const confettiEl=$('#confetti'),soundBtn=$('#soundBtn'),teamWheel=$('#teamWheel'),teamRollStatus=$('#teamRollStatus'),teamRouletteNames=$('#teamRouletteNames');
const SETTINGS_KEY='qbr-settings-v5',NAMES_KEY='qbr-player-names-v1',MATCHUP_KEY='qbr-versus-v5',SOUND_KEY='qbr-sound-v1',TEAMS_KEY='qbr-teams-v5';
const legendaryIds=new Set([144,145,146,150,151,243,244,245,249,250,251,377,378,379,380,381,382,383,384,385,386,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,638,639,640,641,642,643,644,645,646,647,648,649,716,717,718,719,720,721,772,773,785,786,787,788,789,790,791,792,800,801,802,807,808,809,888,889,890,891,892,893,894,895,896,897,898,905,1001,1002,1003,1004,1007,1008,1024,1025]);
const strong=new Set([6,9,65,68,94,130,131,143,149,169,181,196,197,208,212,214,227,230,242,248,254,257,260,282,289,306,330,350,373,376,405,407,445,448,450,461,462,464,468,472,473,475,477,479,485,530,534,553,555,560,567,571,576,579,589,598,609,612,625,628,635,637,681,700,706,715,724,730,748,778,784,812,815,818,823,834,839,841,849,858,861,887,901,903,908,911,914,937,959,964,970,977,983,998,1000,1017,1018,1019]);
const optionColors=['#ef414b','#3178ff','#2fbe67','#c34dff'];
let pokemon=[],currentTeams=JSON.parse(localStorage.getItem(TEAMS_KEY)||'[]'),currentMatchup=JSON.parse(localStorage.getItem(MATCHUP_KEY)||'null');
let playerNames=JSON.parse(localStorage.getItem(NAMES_KEY)||'["Jugador 1","Jugador 2","Jugador 3","Jugador 4"]');
let wheelRotation=0,teamRotation=0,spinning=false,teamRolling=false,soundEnabled=localStorage.getItem(SOUND_KEY)!=='off',audioCtx=null;
while(playerNames.length<4)playerNames.push(`Jugador ${playerNames.length+1}`);
const cfg=()=>({players:+$('#players').value,teamSize:+$('#teamSize').value,level:+$('#level').value,mode:$('#mode').value,legendaries:$('#legendaries').checked,unique:$('#unique').checked,perfectIv:$('#perfectIv').checked});
function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(cfg()))}
function loadSettings(){try{const s=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'null');if(!s)return;$('#players').value=String(s.players??4);$('#teamSize').value=String(s.teamSize??6);$('#level').value=String(s.level??100);$('#mode').value=s.mode||'balanced';$('#legendaries').checked=!!s.legendaries;$('#unique').checked=s.unique!==false;$('#perfectIv').checked=s.perfectIv!==false}catch{}}
function displayName(i){const v=(playerNames[i]||'').trim();return v||`Jugador ${i+1}`}
function renderPlayerInputs(){const count=+$('#players').value;namesEl.innerHTML='';for(let i=0;i<count;i++){const input=document.createElement('input');input.className='player-name-input';input.maxLength=20;input.placeholder=`Jugador ${i+1}`;input.value=playerNames[i]||'';input.oninput=()=>{playerNames[i]=input.value.trimStart();localStorage.setItem(NAMES_KEY,JSON.stringify(playerNames));renderTeamChips();renderRoulette();if(currentTeams.length)renderTeams();renderVersus()};namesEl.appendChild(input)}}
function renderTeamChips(active=-1){const count=+$('#players').value;teamRouletteNames.innerHTML='';for(let i=0;i<count;i++){const chip=document.createElement('div');chip.className='roulette-chip'+(i===active?' active':'');chip.textContent=`J${i+1} · ${displayName(i)}`;teamRouletteNames.appendChild(chip)}}
function ensureAudio(){if(!soundEnabled)return null;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;if(!audioCtx)audioCtx=new AC();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(freq,d=.04,v=.025,type='square',delay=0){const c=ensureAudio();if(!c)return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(c.destination);o.start(t);o.stop(t+d+.02)}
function successSound(){tone(523,.08,.04,'sine');tone(659,.09,.04,'sine',.08);tone(784,.13,.05,'sine',.17)}
function updateSound(){soundBtn.textContent=soundEnabled?'🔊':'🔇';soundBtn.setAttribute('aria-pressed',String(soundEnabled))}
function rand(a){return a[Math.floor(Math.random()*a.length)]}
function poolFor(c){return pokemon.filter(p=>c.legendaries||!legendaryIds.has(p.id))}
function pick(pool,used,c,target='any'){let candidates=pool.filter(p=>!c.unique||!used.has(p.id));if(c.mode==='balanced'&&target!=='any'){const filtered=candidates.filter(p=>target==='strong'?strong.has(p.id):!strong.has(p.id));if(filtered.length)candidates=filtered}const p=rand(candidates);if(c.unique&&p)used.add(p.id);return p}
async function loadPokemon(){statusEl.textContent='Cargando Pokédex…';const cached=localStorage.getItem('qbr-pokemon-v1');if(cached){pokemon=JSON.parse(cached);statusEl.textContent='Pokédex lista · Arena preparada';return}const res=await fetch('https://pokeapi.co/api/v2/pokemon?limit=1025');const data=await res.json();pokemon=data.results.map((p,i)=>({id:i+1,name:p.name}));localStorage.setItem('qbr-pokemon-v1',JSON.stringify(pokemon));statusEl.textContent='Pokédex lista · Arena preparada'}
function makeTeams(){const c=cfg(),pool=poolFor(c),used=new Set(),out=[];for(let t=0;t<c.players;t++){const team=[];for(let i=0;i<c.teamSize;i++){const target=c.mode==='balanced'?(i<Math.ceil(c.teamSize/2)?'strong':'normal'):'any';team.push(pick(pool,used,c,target))}out.push(team)}return out}
async function randomizeTeams(){if(teamRolling)return;if(!pokemon.length)await loadPokemon();const c=cfg();if(c.unique&&poolFor(c).length<c.players*c.teamSize){statusEl.textContent='No hay suficientes especies con esos filtros.';return}teamRolling=true;saveSettings();ensureAudio();const btn=$('#rollBtn'),panel=document.querySelector('.forge-panel');btn.disabled=true;panel.classList.add('rolling');teamRollStatus.textContent='Iniciando sorteo de equipos…';const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;teamRotation+=1440+Math.floor(Math.random()*720);teamWheel.style.transform=`rotateZ(${teamRotation}deg)`;let step=0;const interval=reduced?null:setInterval(()=>{const idx=step%c.players;renderTeamChips(idx);teamRollStatus.textContent=`Buscando equipo para ${displayName(idx)}…`;tone(700+idx*110,.025,.015);step++},180);setTimeout(()=>{if(interval)clearInterval(interval);currentTeams=makeTeams();localStorage.setItem(TEAMS_KEY,JSON.stringify(currentTeams));renderTeamChips();renderTeams(true);teamRollStatus.textContent=`${c.players} equipos listos · Nv. ${c.level}${c.perfectIv?' · IV 31':''}`;statusEl.textContent='Sorteo completado · Equipos guardados en este dispositivo';panel.classList.remove('rolling');btn.disabled=false;teamRolling=false;successSound()},reduced?80:2900)}
function rerollOne(ti,pi){if(!pokemon.length)return;const c=cfg(),pool=poolFor(c),used=new Set();if(c.unique)currentTeams.forEach((team,t)=>team.forEach((p,i)=>{if(!(t===ti&&i===pi))used.add(p.id)}));currentTeams[ti][pi]=pick(pool,used,c);localStorage.setItem(TEAMS_KEY,JSON.stringify(currentTeams));renderTeams()}
function rerollTeam(ti){if(!pokemon.length)return;const c=cfg(),pool=poolFor(c),used=new Set();if(c.unique)currentTeams.forEach((team,t)=>{if(t!==ti)team.forEach(p=>used.add(p.id))});currentTeams[ti]=Array.from({length:c.teamSize},(_,i)=>pick(pool,used,c,c.mode==='balanced'&&i<Math.ceil(c.teamSize/2)?'strong':'any'));localStorage.setItem(TEAMS_KEY,JSON.stringify(currentTeams));renderTeams(true)}
function renderTeams(reveal=false){teamsEl.innerHTML='';const c=cfg();currentTeams.slice(0,c.players).forEach((team,ti)=>{const node=$('#teamTemplate').content.cloneNode(true);const card=node.querySelector('.team-card');if(reveal)card.style.animationDelay=`${ti*90}ms`;node.querySelector('h2').textContent=`J${ti+1} · ${displayName(ti)}`;node.querySelector('.reroll-team').onclick=()=>rerollTeam(ti);const grid=node.querySelector('.pokemon-grid');team.forEach((p,pi)=>{if(!p)return;const pc=$('#pokemonTemplate').content.cloneNode(true),img=pc.querySelector('img');img.src=`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/${p.id}.png`;img.alt=p.name;pc.querySelector('.name').textContent=p.name.replaceAll('-',' ');pc.querySelector('.meta').textContent=`Nv. ${c.level}${c.perfectIv?' · IV31':''}`;pc.querySelector('.reroll-one').onclick=()=>rerollOne(ti,pi);grid.appendChild(pc)});teamsEl.appendChild(node)})}
function names(ids){return ids.map(displayName).join(' + ')}
function getMatchOptions(){const n=+$('#players').value;if(n===4)return[{players:4,teamA:[0,1],teamB:[2,3]},{players:4,teamA:[0,2],teamB:[1,3]},{players:4,teamA:[0,3],teamB:[1,2]}];if(n===3)return[{players:3,teamA:[1],teamB:[2],bye:0},{players:3,teamA:[0],teamB:[2],bye:1},{players:3,teamA:[0],teamB:[1],bye:2}];return[{players:2,teamA:[0],teamB:[1]},{players:2,teamA:[1],teamB:[0]}]}
function optionText(o){if(o.players===3)return{main:`${names(o.teamA)} VS ${names(o.teamB)}`,sub:`Descansa ${displayName(o.bye)}`};if(o.players===2)return{main:`${names(o.teamA)} VS ${names(o.teamB)}`,sub:'1 contra 1'};return{main:`${names(o.teamA)} VS ${names(o.teamB)}`,sub:'2 contra 2'}}
function renderRoulette(){const opts=getMatchOptions(),span=360/opts.length;wheelEl.style.background=`conic-gradient(from -90deg,${opts.map((_,i)=>`${optionColors[i]} ${(i/opts.length)*100}% ${((i+1)/opts.length)*100}%`).join(',')})`;wheelMarkersEl.innerHTML='';rouletteOptionsEl.innerHTML='';opts.forEach((o,i)=>{const m=document.createElement('div');m.className='wheel-marker';const a=(-90+span*(i+.5))*Math.PI/180;m.style.left=`${50+Math.cos(a)*35}%`;m.style.top=`${50+Math.sin(a)*35}%`;m.style.transform='translate(-50%,-50%)';m.innerHTML=`<span>${i+1}</span>`;wheelMarkersEl.appendChild(m);const item=document.createElement('div');item.className='roulette-option'+(currentMatchup?.optionIndex===i?' is-winner':'');const t=optionText(o);item.innerHTML=`<div class="option-main">${t.main}</div><div class="option-sub">${t.sub}</div>`;rouletteOptionsEl.appendChild(item)})}
function renderVersus(reveal=false){versusEl.classList.remove('reveal');if(!currentMatchup||currentMatchup.players!==+$('#players').value){versusEl.innerHTML='<div class="versus-placeholder">Gira la ruleta para revelar la combinación.</div>';return}const bye=currentMatchup.bye!==undefined?`<div class="bye">Descansa: <strong>${displayName(currentMatchup.bye)}</strong></div>`:'';versusEl.innerHTML=`<div class="side"><span class="side-label">Equipo A</span><strong>${names(currentMatchup.teamA)}</strong></div><div class="vs-badge">VS</div><div class="side"><span class="side-label">Equipo B</span><strong>${names(currentMatchup.teamB)}</strong></div>${bye}`;if(reveal){void versusEl.offsetWidth;versusEl.classList.add('reveal')}}
function confetti(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;confettiEl.innerHTML='';for(let i=0;i<34;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.background=optionColors[i%3];p.style.setProperty('--x',`${Math.round((Math.random()-.5)*500)}px`);p.style.setProperty('--y',`${Math.round(-70+Math.random()*290)}px`);p.style.setProperty('--r',`${Math.round((Math.random()-.5)*800)}deg`);confettiEl.appendChild(p)}setTimeout(()=>confettiEl.innerHTML='',1100)}
function randomizeVersus(){if(spinning)return;spinning=true;ensureAudio();const btn=$('#versusBtn'),opts=getMatchOptions(),winner=Math.floor(Math.random()*opts.length),next={...opts[winner],optionIndex:winner},span=360/opts.length,target=((-(winner+.5)*span)%360+360)%360,current=((wheelRotation%360)+360)%360;wheelRotation+=5*360+(target-current+360)%360;btn.disabled=true;versusEl.innerHTML='<div class="versus-placeholder">Sorteando enfrentamiento…</div>';wheelEl.style.transform=`rotateZ(${wheelRotation}deg)`;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let ticks=reduced?null:setInterval(()=>tone(1180,.025,.014),110);setTimeout(()=>{if(ticks)clearInterval(ticks);currentMatchup=next;localStorage.setItem(MATCHUP_KEY,JSON.stringify(currentMatchup));spinning=false;btn.disabled=false;renderRoulette();renderVersus(true);successSound();confetti()},reduced?80:3650)}
$('#rollBtn').onclick=randomizeTeams;$('#versusBtn').onclick=randomizeVersus;soundBtn.onclick=()=>{soundEnabled=!soundEnabled;localStorage.setItem(SOUND_KEY,soundEnabled?'on':'off');updateSound()};
$('#players').onchange=()=>{saveSettings();renderPlayerInputs();renderTeamChips();renderRoulette();renderVersus();if(currentTeams.length){currentTeams=currentTeams.slice(0,+$('#players').value);renderTeams()}};['teamSize','level','mode','legendaries','unique','perfectIv'].forEach(id=>$('#'+id).onchange=saveSettings);
loadSettings();renderPlayerInputs();renderTeamChips();renderRoulette();renderVersus();updateSound();if(currentTeams.length)renderTeams();loadPokemon().catch(()=>statusEl.textContent='Sin conexión: usaré la Pokédex en caché cuando esté disponible.');
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw-v5.js');